---
name: Build and deploy Terraform
on:
  push:
    branches: [ develop , stage, master]
jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    env:
      VAR_FILE: ${{ github.ref == 'refs/heads/develop' && 'env.dev.tfvars' || github.ref == 'refs/heads/stage' && 'env.stage.tfvars' || github.ref == 'refs/heads/master' && 'env.prod.tfvars' }}
      REGION: us-east-1
      PLAN: ${{ github.ref == 'refs/heads/develop' && 'dev' || github.ref == 'refs/heads/stage' && 'stage' || github.ref == 'refs/heads/master' && 'prod' }}
      ACCESS_KEY: AKIA5FTZAIMGGYXFE5NJ
      SECRET_KEY: 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

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ env.ACCESS_KEY }}
        aws-secret-access-key: ${{ env.SECRET_KEY }}
        aws-region: ${{ env.REGION }}
        
    - name: Init terraform
      run: terraform init

    - name: Terraform validate
      run: terraform validate

    - name: Terraform plan 
      run: terraform plan -var-file=environment/${{ env.PLAN }}/${{ env.VAR_FILE }} -out=${{ env.PLAN }} -input=false

    - name: Terraform apply 
      run: terraform apply ${{ env.PLAN }}

     